### ISSUE TITLE
How to estimate the depth of a custom image？

### ISSUE THREAD

**Issue by QinZiwen** [VCL3D/SphericalViewSynthesis#1]
I have some panorama image. Their resolution is 5760(width)*2880(height). How to use “SphericalViewSynthesis” to infer the depth the image ?

Thank you very much!

**Comment by zuru** [comment]
Hi,

just added [`infer.py`](https://github.com/VCL3D/SphericalViewSynthesis/blob/master/infer.py):
- `--input_path`: path to the input image
- `--weights`: pre-trained model weights, available @ https://github.com/VCL3D/SphericalViewSynthesis/releases 
- `--gpu`: GPU id or -1 for cpu

It will run inference and save an `*.exr` depth map, with the original filename suffixed with `_depth` and a resolution of `512 x 256`.
