### ISSUE TITLE
Need to know more about disparity formula

### ISSUE THREAD

**Issue by Jarrome** [VCL3D/SphericalViewSynthesis#3]
Hi, authors, I asked this question in last issue but you closed it. So I refreshed it in a new issue.

Actually, in [Spherical View Synthesis for Self-Supervised 360o Depth Estimation](url), the vertical disparity formula 
![Screen Shot 2020-06-30 at 10 15 59 AM](https://user-images.githubusercontent.com/13412144/86075538-c9c47400-baba-11ea-95b6-db3c8c06127d.png)
I find it fancy but I personally cannot relate it to the Law of sines.
In addition, I find lines of code using the formula but have no idea why the disparity looks like this.

The work is nice, I just want to better understand it.

_Originally posted by @Jarrome in https://github.com/VCL3D/SphericalViewSynthesis/issues/2#issuecomment-651481515_

**Comment by zuru** [comment]
Hi Jarrome,

indeed the notation is confusing. 
To set it straight:

- The angular disparity `gamma`, corresponds to the displacement of the `phi` and `theta` angles, i.e. `gamma` = (`phi_displacement`, `theta_displacement`). 
- The partial derivatives relate the angular displacements to the cartesian displacements.
- For the vertical disparity case, we only have displacement along the `y-axis`.
- In addition, the longitudinal partial derivative w.r.t the displacement along the `y-axis` is zero, thus the displacement of phi is zero, i.e. `phi_displacement = 0`.

We are then left with angular disparity being (0, `theta_displacement`), with the latter being `theta_displacement = -sin(theta) * y_displacement / r`.

**Comment by Jarrome** [comment]
Hi, zuru,

Thank you. But that's not what I'm confusing.

Actually, the **y_displacement** is the **baseline** on y-axis, r is the depth.
So my understanding is, if we follow the Law of sine, the formula should be like

`sin(theta_displacement) = -sin(theta) * y_displacement / r` instead.

Maybe I miss something? Or the ignoring of sine is just for the convenience of deep learning?

**Comment by zuru** [comment]
Hi Jarrome,

can you please check the law of sines document in #2 can then update the formula using the notation (angles and segments) in that document?

I think the confusion arises from the frame of reference, i.e. which `r` and `theta` are used, and the fact that they are not aligned (i.e. bottom/top and top/bottom).

**Comment by Jarrome** [comment]
Hi, zuru,

Yes, zuru, the `sin(theta_displacement) = -sin(theta) * y_displacement / r` might be inaccurate but my idea is `theta_displacement` should be solved with `arcsin` or in your law of sines document Eq. (7) a `arctan` to solve the `\gamma`.

While the paper is with `theta_displacement = -sin(theta) * y_displacement / r`, that's what I'm confusing.
